[permissions]
command = "Permission to use the base command"

[core]
member_nf = "Member not found"
help_nf = "No help pages found"

[help]
title = "Help for `{0}`:"
permission = "**Permission**: `{0}`"
syntax = "**Usage syntax**:"
url = "**Docs**: {0}"
examples = "**Examples**:"

#FUN
[commands.fun]
    # Anime
    [commands.fun.anime]
    request = "Requested by"
    status = "Status"
    episodes = "Episodes"
    rating = "Rating"
    rank = "Rank"
    popularity = "Popularity"
    first = "First Airing"
    last = "Last Airing"
    next = "Next Airing"
    age = "Age Rating"
    description = "Search for anime information"
    # Color
    [commands.fun.color]
    error = "Error writing color"
    notcolor = "That's not a color"
    description = "Show the color of a informed hex code"
    # Flip
    [commands.fun.flip]
    heads = "flipped a coin and got **Heads**."
    tails = "flipped a coin and got **Tails**."
    description = "Flip's a coin"
    # Roll
    [commands.fun.roll]
    roll = "rolled"
    nanumber = "not a number"
    description = "Roll's a random number"
    [commands.fun.quote]
    description = "Quote is a simple command which \"generate\" a random quote every time that is called."
[commands.mod]
    # Prune
    [commands.mod.prune]
    del = "Messages deleted. This message will auto-destruct in 5 seconds."
    # Ban
    [commands.mod.ban]
    description = "Bans a member from the guild, deleting all messages from that user for the past 7 days."
    noreason = "No reason specified."
    banned = "Banned {0}."
    interact = "No permission to ban {0}."
# NSFW
[commands.nsfw]
load = "Click here if image doesn't load"
tags = "Tags"
request = "Requested by "
rating = "Rating"
size = "Size"
score = "Score"
    [commands.nsfw.rule34]
    description = "Searching for image in Rule34"
    [commands.nsfw.danbooru]
    description = "Searching for image in Danbooru"
# WIKI
[commands.wiki]
    #Hearthstone
    [commands.wiki.hearthstone]
    404 = "Card Not Found!"
    description = "Search Hearthstone card by name."