[permissions]
command = "Permission to use the base command"
nsfw = "Permission to use the command on nsfw channels"
user = "You do not have permission to do this. Missing `{0}`."
bot = "I do not have permission to do this. Missing `{0}`."

[core]
member_nf = "Member not found"
help_nf = "No help pages found"
not_nsfw = "This channel isn't nsfw"
not_number = "`{0}` is not a number"
not_boolean = "`{0}` is not a boolean. (Must be true/false)"

[help]
title = "Help for `{0}`:"
permission = "**Permission**: `{0}`"
syntax = "**Usage syntax**:"
url = "**Docs**: {0}"
examples = "**Examples**:"

[search]
role = "No roles found named `{0}`."
permission = "No permissions found with name `{0}`."
channel = "No channel named `{0}` found."
voice = "No voice channel named `{0}` found."
member = "No members named `{0}` found."

[parts]
days = "{0} days"
hours = "{0} hours"
minutes = "{0} minutes"
seconds = "{0} seconds"
day = "{0} day"
hour = "{0} hour"
minute = "{0} minute"
second = "{0} second"

[features]
keeproles = "[Keep Roles] Added {0} roles back."

[options]
keeproles = "Readds roles when a member joins"
language = "Server language, used for audit reasons, modlog, etc.."
starboard = "Starboard channel"
playlist = "Active playlist id"
[options.embed]
title = "Option `{0}`:"
type = "**Type**:"
default = "**Default**:"
current = "**Current**:"
list = "Available options:"
page = "Page [{0}/{1}]"

[embeds]
    [embeds.ignored]
    title = "Ignored channels:"
    page = "Page [{0}/{1}]"
    [embeds.reactionroles]
    title = "Reaction Roles"
    page = "Page [{0}/{1}]"
    line = "Reaction {0} in {1} (Role `{2}`)"
    [embeds.leaderboard]
    title = "{0} Leaderboard"
    line = "{0}#{1} - {2} - {3}"

[commands.core]
    # Help
    [commands.core.help]
    description = "Searches for help on the command database."
    # Permissions
    [commands.core.permissions]
    description = "Manages role permissions for bot features"
    for = "Permissions for `{0}`:"
    cleared = "Permissions cleared for `{0}`."
    updated = "Permissions updated."
    # Options
    [commands.core.options]
    description = "Manage guild options"
    updated = "Updated `{0}`."
    not_found = "Option not found."
    # Ignore
    [commands.core.ignore]
    description = "Manage ignored channels"
    added = "{0} is now ignored."
    removed = "{0} is no longer ignored."
    is_ignored = "{0} is already ignored."
    is_not_ignored = "{0} is not currently ignored."
    empty = "No channels are currently ignored."
    # Language
    [commands.core.language]
    description = "Find out a users language or update your own."
    unknown = "Unknown language."
    updated = "Language updated to {0}."
    target = "{0}'s preferred language is {1}."
    # Privacy
    [commands.core.privacy]
    description = "Links to Lindsey's privacy policy."
    link = "You can review our privacy policy at <https://notfab.net/Lindsey/privacy.txt>"
    # Prefix
    [commands.core.prefix]
    description = "Allows you to customize the bot's prefix."
    changed = "Prefix changed to `{0}`."

[commands.economy]
not_enough = "Not enough cookies."
    win = "You win {0} cookies!"
    [commands.economy.cookies]
    description = "Find out how many cookies a user (like yourself) has!"
    self = "You have {0} :cookie:."
    target = "{0} has {1} :cookie:."
    daily_already = "You already received your daily cookies. Try again in {0}."
    daily = "+{0} :cookie:! Come back tomorrow to start your streak!"
    daily_streak = "+{0} :cookie:! (Streak = {1}) Come back tomorrow for more cookies!"
    [commands.economy.leaderboard]
    description = "Lindsey Leaderboards"
    unknown_type = "Unknown Leaderboard Type, available: `{0}`."

[commands.items]
not_enough = "Not enough items."

[commands.fun]
    lost = "You lost."
    # Anime
    [commands.fun.anime]
    request = "Requested by"
    status = "Status"
    episodes = "Episodes"
    rating = "Rating"
    rank = "Rank"
    popularity = "Popularity"
    first = "First Airing"
    last = "Last Airing"
    next = "Next Airing"
    age = "Age Rating"
    description = "Searches for anime information"
    type = "Type"
    score = "Score"
    members = "Members"
    airing = "Airing"
    finished = "Finished"
    404 = "Anime Not Found!"
    # Color
    [commands.fun.color]
    error = "Error writing color"
    notcolor = "That's not a color"
    description = "Shows the color of an informed HEX code"
    # Flip
    [commands.fun.flip]
    heads = "flipped a coin and got **Heads**."
    tails = "flipped a coin and got **Tails**."
    description = "Flips a coin."
    # Roll
    [commands.fun.roll]
    roll = "rolled"
    nanumber = "not a number"
    description = "Rolls a random number."
    [commands.fun.quote]
    description = "Quote is a simple command which generates a random quote every time that it is called."
    [commands.fun.define]
    description = "Defines a given word."
    no_definitions = "No definitions found for {0}, can you define it?"
    # Scramble
    [commands.fun.scramble]
    description = "Starts a scramble game (Answer by simply saying the correct word in the chat)."
    start = "The word is `{0}`, you have 1 minute to guess"
    fail = "Oops, Timed out! word: `{0}`"
    active = "There is already a scramble game on this server"
    # Profile
    [commands.fun.profile]
    description = "Looks up someone's profile"
    failed = "Failed to load that profile."
    error = "Error while trying to load that profile."
    # Starboard
    [commands.fun.starboard]
    description = "Star all the important messages."
    enabled = "Starboard enabled in {0}."
    disabled = "Starboard is now disabled."
    # BlackJack
    [commands.fun.blackjack]
    draw = "draw"
    description = "Blackjack! also called 21"
    price = "Bet mus be between 1 and 5000"
    # Slot
    [commands.fun.slot]
    description = "Slot machine!"
    start = "{0} started the slot machine!"
    values = "Price : {0} | Jackpot: {1}"

[commands.mod]
    # Prune
    [commands.mod.prune]
    del = " Messages deleted. This message will auto-destruct in 5 seconds."
    err = "Type a number between 2 and 99"
    description = "Deleted messages"
    # Ban
    [commands.mod.ban]
    description = "Bans a member from the guild, deleting all messages from that user for the past 7 days."
    noreason = "No reason specified."
    banned = "Banned {0}."
    interact = "No permission to ban {0}."
    # Multiban
    [commands.mod.multiban]
    description = "Bans a list of members from the guild, deleting all messages from that user for the past 7 days."
    banned = "Banned {0}."
    member_nf = "{0} not found"
    ban = "Banned {0} users"
    audit = "{0} - Multiban"
    # Kick
    [commands.mod.kick]
    description = "Kicks a member from the guild."
    noreason = "No reason specified."
    kicked = "Kicked {0}."
    interact = "No permission to kick {0}."
    # Reaction Roles
    [commands.mod.reactionroles]
    description = "Adds roles based on reactions to a message"
    started = "Started reaction role creation. Please react to any message in the server with the appropriate emote/emoji. [5m Timeout]"
    created = "Reaction role created successfully. Name {0} - {1}"
    removed = "Removed reaction role {0}."
    failed_remove = "Reaction role named {0} not found."
    failed_create = "Failed to start a reaction role creation, one is already in progress."
    failed_name_too_big = "Reaction role name must not exceed 18 characters."
    empty = "No reaction roles are configured."
    # Strike
    [commands.mod.strike]
    description = "Strikes a user (warnings/punishments)"
    noreason = "No reason specified"
    interact = "This user is immune to strikes."
    message = "You have received a strike in **{0}**. You now have a total of **{2}** strike(s).\nReason: `{1}`."
    striked = "User striked. Total strikes `{0}` [+{1}]."
    # Softban
    [commands.mod.softban]
    description = "Softbans (ban+unban) a member from the guild, deleting all messages from that user for the past 7 days."
    noreason = "No reason specified."
    banned = "SoftBanned {0}."
    interact = "No permission to softban {0}."
    message = "You have been softbanned from **{0}**. You may join back if you desire.\nReason: `{1}`."
    # Slowmode
    [commands.mod.slowmode]
    description = "Activates slowmode on this channel."
    active = "Slowmode enabled (T={0}s)"
    invalid = "Invalid max number of seconds for slowmode. Limit {0}s."
    # Voice
    [commands.mod.voice]
    description = "Moves or splits voice members from one channel to another."
    moving = "Moving members..."
    splitting = "Splitting members..."
    permission_move = "No permission to move `{0}`."

# NSFW
[commands.nsfw]
load = "Click here if image doesn't load"
tags = "Tags"
request = "Requested by "
rating = "Rating"
size = "Size"
score = "Score"
[commands.nsfw.description]
rule34 = "Searches for an image on Rule34"
    danbooru = "Searches for an image on Danbooru"
    gelbooru = "Searches for an image on Gelbooru"
    konachan = "Searches for an image on Konachan"
    Safebooru = "Searches for an image on e926"
    e621 = "Searches for an image on e621"
    e926 = "Searches for an image on e926"
# WIKI
[commands.wiki]
    #Hearthstone
    [commands.wiki.hearthstone]
    404 = "Card Not Found!"
    description = "Search Hearthstone card by name."
    # Pokedex
    [commands.wiki.pokedex]
    id = "ID"
    height = "Height"
    weight = "Weight"
    type = "Type"
    description = "Pokemon Wiki."
    404 = "Pokemon Not Found!"

# PlayList
[commands.playlist]
description = "Manage your playlists."
no_active = "No active playlists. (Try using `L!playlist use`)"
locked = "Missing permissions to edit this playlist."
not_found = "No playlists named `{0}` found."
curator_added = "Added `{0}` as curator on `{1}`."
curator_removed = "Removed `{0}` as curator from `{1}`."
limit_reached = "You have reached the playlist limit. [{0}/{1}]"
created = "Playlist `{0}` created. "
deleted = "Playlist `{0}` deleted."
no_songs = "No songs in this playlist yet."
shuffle_enabled = "Shuffle mode is now enabled."
shuffle_disabled = "Shuffle mode is now disabled."
not_imgur = "Not a valid imgur URL, please grab the direct image link (i.imgur.com/id.png)"
logo_updated = "Updated the logo for `{0}`."
not_security = "Unknown security name `{0}`, available are `PUBLIC, SHARED, PRIVATE`."
security_updated = "Updated security for `{0}` to `{1}`."
active = "PlayList `{0}` is now active."

# Music
[commands.music]
    # Connect
    [commands.music.connect]
    description = "Makes Lindsey connect to a voice channel."
    not_in_vc = "No channels specified and you are not in a voice channel."
    failed = "Failed to join voice channel (No permission? Channel is full?)"
    connected = "Connected to `{0}`."
    [commands.music.disconnect]
    description = "Stops the playback and disconnects from the current voice channel."
    failed = "Not currently connected."
    disconnected = "Disconnected. Requested by `{0}`."
    [commands.music.add]
    description = "Adds a song (or list of songs) to the playlist"
    not_supported = "This provider is not supported."
    failed = "Failed to load track. Reason: `{0}`."
    added_multiple = "Added {0} songs to the playlist."
    added_one = "Added {0} to the playlist."
    [commands.music.remove]
    description = "Removes all songs from the playlist that match the input."
    removed = "Removed {0} songs from the playlist."
    [commands.music.play]
    description = "Plays a specific song, or skips to the next one."
    not_found = "No songs named `{0}` found."
    failed_voice = "Failed to start playback. No voice connection active."
    failed_songs = "Failed to start playback. No songs found."
    failed_internal = "Failed to start playback. Internal error."
    playing = "`[{0}]` - {1}"
