[permissions]
command = "Permission to use the base command"
nsfw = "Permission to use the command on nsfw channels"

[core]
member_nf = "Member not found"
help_nf = "No help pages found"
not_nsfw = "This channel isn't nsfw"

[help]
title = "Help for `{0}`:"
permission = "**Permission**: `{0}`"
syntax = "**Usage syntax**:"
url = "**Docs**: {0}"
examples = "**Examples**:"

[search]
role = "No roles found named `{0}`."
permission = "No permissions found with name `{0}`."

[commands.core]
    # Help
    [commands.core.help]
    description = "Searches for help on the command database."
    # Permissions
    [commands.core.permissions]
    description = "Manages role permissions for bot features"
    for = "Permissions for `{0}`:"
    cleared = "Permissions cleared for `{0}`."
    updated = "Permissions updated."

[commands.fun]
    # Anime
    [commands.fun.anime]
    request = "Requested by"
    status = "Status"
    episodes = "Episodes"
    rating = "Rating"
    rank = "Rank"
    popularity = "Popularity"
    first = "First Airing"
    last = "Last Airing"
    next = "Next Airing"
    age = "Age Rating"
    description = "Searches for anime information"
    # Color
    [commands.fun.color]
    error = "Error writing color"
    notcolor = "That's not a color"
    description = "Shows the color of an informed HEX code"
    # Flip
    [commands.fun.flip]
    heads = "flipped a coin and got **Heads**."
    tails = "flipped a coin and got **Tails**."
    description = "Flips a coin."
    # Roll
    [commands.fun.roll]
    roll = "rolled"
    nanumber = "not a number"
    description = "Rolls a random number."
    [commands.fun.quote]
    description = "Quote is a simple command which generates a random quote every time that it is called."
[commands.mod]
    # Prune
    [commands.mod.prune]
    del = "Messages deleted. This message will auto-destruct in 5 seconds."
    # Ban
    [commands.mod.ban]
    description = "Bans a member from the guild, deleting all messages from that user for the past 7 days."
    noreason = "No reason specified."
    banned = "Banned {0}."
    interact = "No permission to ban {0}."
    # Kick
    [commands.mod.kick]
    description = "Kicks a member from the guild."
    noreason = "No reason specified."
    kicked = "Kicked {0}."
    interact = "No permission to kick {0}."
# NSFW
[commands.nsfw]
load = "Click here if image doesn't load"
tags = "Tags"
request = "Requested by "
rating = "Rating"
size = "Size"
score = "Score"
    [commands.nsfw.rule34]
    description = "Searches for an image on Rule34"
    [commands.nsfw.danbooru]
    description = "Searches for an image on Danbooru"
# WIKI
[commands.wiki]
    #Hearthstone
    [commands.wiki.hearthstone]
    404 = "Card Not Found!"
    description = "Search Hearthstone card by name."
