bot:
  token: ''
  integrations:
    rapidapi: ''
    kitsu: ''
    twitchClient: ''
    twitchKey: ''
  controller:
    url: 'http://localhost:8081'
    token: ''
    id: 'master'
spring:
  datasource:
    url: jdbc:h2:mem:lindsey
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'

---

bot:
  token: ''
  integrations:
    rapidapi: ''
    kitsu: ''
    twitchClient: ''
    twitchKey: ''
  controller:
    url: 'http://localhost:8081'
    token: ''
    id: 'master'
spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/staging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 480000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
