bot:
  token: ''
  integrations:
    rapidapi: ''
    kitsu: ''
    twitchClient: ''
    twitchKey: ''
spring:
  datasource:
    url: jdbc:h2:mem:lindsey
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
  data:
    mongodb:
      username: 'root'
      password: 'root'
      host: 'localhost'
      authentication-database: admin
      database: test

---

bot:
  token: ''
  integrations:
    rapidapi: ''
    kitsu: ''
    twitchClient: ''
    twitchKey: ''
spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/staging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 480000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 'localhost'
  data:
    mongodb:
      username: 'root'
      password: 'root'
      host: 'localhost'
      authentication-database: admin
      database: lindsey
