[core.permission]
generic = "Permission to use the base command"

[core.commands.fun.anime]
request = "Requested by"
status = "Status"
episodes = "Episodes"
rating = "Rating"
rank = "Rank"
popularity = "Popularity"
first = "First Airing"
last = "Last Airing"
next = "Next Airing"
age = "Age Rating"

[core.commands.fun.color]
error = "Error writing color"

[core.commands.fun.flip]
heads = "flipped a coin and got **Heads**."
tails = "flipped a coin and got **Tails**."

[core.commands.fun.roll]
roll = "rolled"
nanumber = "not a number"

[core.commands.moderation.prune]
del = "Messages deleted. This message will auto-destruct in 5 seconds."

[core.commands.nsfw]
load = "Click here if image doesn't load"
tags = "Tags"
request = "Requested by "
rating = "Rating"
size = "Size"
score = "Score"
